language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_script:    
  - npm install -g @angular/cli
script:
- lint
- npm run test-headless
#- npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
#- ng build --prod --base-href https://spegusess.github.io/Tour-of-Heroes/
